#!/bin/bash

apt install -y  --no-install-recommends \
apt-transport-https \
ca-certificates \
curl \
dirmngr \
gnupg-agent \
software-properties-common \
bash-completion \
command-not-found \
dialog \
net-tools \
git \
gnupg2 \
locales \
lsb-release  \
adduser \
gnupg \
hostname

curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | apt-key add -
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | tee /etc/apt/sources.list.d/tailscale.list
apt update
apt install tailscale
